[build]
  publish = "."  # Assuming your site files are in the root directory

# Handle /story/[id] paths by routing to story.html
[[redirects]]
  from = "/story/*"
  to = "/story.html"
  status = 200

# Handle /character/[id] paths by routing to character.html
[[redirects]]
  from = "/character/*"
  to = "/character.html"
  status = 200

# Handle all other paths to support SPA navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200